apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true

  - name: TimescaleDB
    type: postgres
    url: timescaledb:5432
    user: nodesense
    secureJsonData:
      password: nodesensepass
    jsonData:
      database: nodesense
      sslmode: disable
      timescaledb: true
